kind: template
load: deploy-microservices.yml
data:
  service: wiki
  AWS_REGION: eu-west-1
  LOG_LEVEL: info
  ASYNC_CONTEXT: 1
  env_var_from_secret:
    REGISTRY_PASSWORD: REGISTRY_PASSWORD
    GITHUB_TOKEN: git_pat
    DRONE_TOKEN: DRONE_TOKEN
    SENTRY_AUTH_TOKEN: SENTRY_AUTH_TOKEN
    ALLOW_PUSH_DEPLOYMENT: ALLOW_PUSH_DEPLOYMENT
    AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
    SONAR_TOKEN: SONAR_TOKEN
    DEV_DATABASE_URL: WIKI_DEV_DATABASE_URL
    PROD_DATABASE_URL: WIKI_PROD_DATABASE_URL
  dev:
    values:
      deployment.secret: arn:aws:secretsmanager:eu-west-1:221581667315:secret:/wiki/dev-Pgb1Q5
      externalPostgresql.databaseURL: $DEV_DATABASE_URL
      ingress.host: wiki.deel.training
      nodeSelector: development
  prod:
    values:
      deployment.secret: arn:aws:secretsmanager:eu-west-1:221581667315:secret:/wiki/prod-DPoZMs
      externalPostgresql.databaseURL: $PROD_DATABASE_URL
      ingress.host: wiki.deel.network
      nodeSelector: production
